name: Build & Test Functions

on:
  workflow_dispatch:
  pull_request:

jobs:
  compile-workspace:
    runs-on: ubuntu-latest
    name: Test Functions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Functions
        shell: bash
        run: |
          cargo test